---

- name: Ensure directory exists for local self-signed TLS certs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ etcd.data.ssl.dir }}"
    - "{{ etcd.data.ssl.dir }}/ca"
    - "{{ etcd.data.ssl.dir }}/transport"
    - "{{ etcd.data.ssl.dir }}/{{ ansible_hostname }}"

- name: Create local certificates directory
  become: false
  local_action:
    module: file
    state: directory
    path: certificates/etcd
    recurse: true

- include_tasks: certificates/gen-ca.yml
- include_tasks: certificates/gen-peer.yml
- include_tasks: certificates/gen-transport.yml
