---

- name: Ensure directory exists for local self-signed TLS certs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ etcd_data_ssl_dir }}"
    - "{{ etcd_data_ssl_dir }}/{{ etcd_data_ssl_ca_dir }}"
    - "{{ etcd_data_ssl_dir }}/{{ etcd_data_ssl_transport_dir }}"
    - "{{ etcd_data_ssl_dir }}/{{ etcd_data_ssl_peer_dir }}"

- name: Create local certificates directory
  become: false
  local_action:
    module: file
    state: directory
    path: certificates/etcd
    recurse: true

- include_tasks: certificates/gen-ca.yml
- include_tasks: certificates/gen-peer.yml
- include_tasks: certificates/gen-transport.yml
