---

### Start etcd container as described in official CoreOS docs
### https://coreos.com/etcd/docs/latest/v2/docker_guide.html

- name: Start container
  docker_container:
    name: etcd
    image: "{{ etcd.image.repo }}:{{ etcd.image.tag }}"
    ports:
      - "{{ etcd.network.ports.peers }}:{{ etcd.network.ports.peers }}"
      - "{{ etcd.network.ports.listen }}:{{ etcd.network.ports.listen }}" 
    volumes:
      - "{{ etcd.data.dir.external }}:{{ etcd.data.dir.internal }}:rw,Z"
      - "{{ etcd.data.ssl.dir }}:{{ etcd.data.ssl.internal }}:ro,Z"
    command: [
        "--name", "{{ ansible_hostname }}",
        "--data-dir","/datadir",
        ##Client listen options
        "--client-cert-auth",
        "--trusted-ca-file","{{ etcd.data.ssl.internal }}/ca/{{ etcd.data.ssl.ca.cert }}",
        "--cert-file","{{ etcd.data.ssl.internal }}/transport/{{ etcd.data.ssl.transport.cert }}", 
        "--key-file","{{ etcd.data.ssl.internal }}/transport/{{ etcd.data.ssl.transport.key }}",
        "-advertise-client-urls","{{ etcd.network.proto.listen }}://{{ hostvars[inventory_hostname]['ansible_%s' | format(etcd.network.interface)].ipv4.address }}:{{ etcd.network.ports.listen }}",
        "-listen-client-urls","{{ etcd.network.proto.listen }}://0.0.0.0:{{ etcd.network.ports.listen }}", 
        "-initial-cluster-token","{{ etcd.cluster.name }}",
        "-initial-cluster","{% for node in groups[etcd.hosts_group] %}{{ node }}={{ etcd.network.proto.peers }}://{{ hostvars[node]['ansible_%s' | format(etcd.network.interface)].ipv4.address }}:{{ etcd.network.ports.peers }}{% if loop.index < groups[etcd.hosts_group]|length %},{% endif %}{% endfor %}",
        ##Peer listen options
        "-listen-peer-urls","{{ etcd.network.proto.peers }}://0.0.0.0:{{ etcd.network.ports.peers }}",
        "-initial-advertise-peer-urls","{{ etcd.network.proto.peers }}://{{ hostvars[inventory_hostname]['ansible_%s' | format(etcd.network.interface)].ipv4.address }}:{{ etcd.network.ports.peers }}",
        "--peer-client-cert-auth",
        "--peer-key-file","{{ etcd.data.ssl.internal }}/{{ ansible_hostname }}/{{ ansible_hostname }}-peer-client.key",
        "--peer-cert-file","{{ etcd.data.ssl.internal }}/{{ ansible_hostname }}/{{ ansible_hostname }}-peer-client.pem",
        "--peer-trusted-ca-file","{{ etcd.data.ssl.internal }}/ca/{{ etcd.data.ssl.ca.cert }}",
        "--debug"
    ]
