---

### Start etcd container as described in official CoreOS docs
### https://coreos.com/etcd/docs/latest/v2/docker_guide.html

- name: Start container
  docker_container:
    name: etcd
    image: "{{ etcd_image_repo }}:{{ etcd_image_tag }}"
    ports:
      - "{{ etcd_network_ports_peers }}:{{ etcd_network_ports_peers }}"
      - "{{ etcd_network_ports_listen }}:{{ etcd_network_ports_listen }}" 
    volumes:
      - "{{ etcd_data_dir_external }}:{{ etcd_data_dir_internal }}:rw,Z"
      - "{{ etcd_data_ssl_dir }}:{{ etcd_data_ssl_internal }}:ro,Z"
    command: [
        "--name", "{{ ansible_hostname }}",
        "--data-dir","{{ etcd_data_dir_internal }}",
        ##Client listen options
        "--client-cert-auth",
        "--trusted-ca-file","{{ etcd_data_ssl_internal }}/{{ etcd_data_ssl_ca_dir }}/{{ etcd_data_ssl_ca_cert }}",
        "--cert-file","{{ etcd_data_ssl_internal }}/{{ etcd_data_ssl_transport_dir }}/{{ etcd_data_ssl_transport_cert }}", 
        "--key-file","{{ etcd_data_ssl_internal }}/{{ etcd_data_ssl_transport_dir }}/{{ etcd_data_ssl_transport_key }}",
        "-advertise-client-urls","{{ etcd_network_proto_listen }}://{{ hostvars[inventory_hostname]['ansible_%s' | format(etcd_network_interface)].ipv4.address }}:{{ etcd_network_ports_listen }}",
        "-listen-client-urls","{{ etcd_network_proto_listen }}://0.0.0.0:{{ etcd_network_ports_listen }}", 
        "-initial-cluster-token","{{ etcd_cluster_name }}",
        "-initial-cluster","{% for node in groups[etcd_hosts_group] %}{{ node }}={{ etcd_network_proto_peers }}://{{ hostvars[node]['ansible_%s' | format(etcd_network_interface)].ipv4.address }}:{{ etcd_network_ports_peers }}{% if loop.index < groups[etcd_hosts_group]|length %},{% endif %}{% endfor %}",
        ##Peer listen options
        "-listen-peer-urls","{{ etcd_network_proto_peers }}://0.0.0.0:{{ etcd_network_ports_peers }}",
        "-initial-advertise-peer-urls","{{ etcd_network_proto_peers }}://{{ hostvars[inventory_hostname]['ansible_%s' | format(etcd_network_interface)].ipv4.address }}:{{ etcd_network_ports_peers }}",
        "--peer-client-cert-auth",
        "--peer-key-file","{{ etcd_data_ssl_internal }}/{{ etcd_data_ssl_peer_dir }}/{{ etcd_data_ssl_peer_key }}",
        "--peer-cert-file","{{ etcd_data_ssl_internal }}/{{ etcd_data_ssl_peer_dir }}/{{ etcd_data_ssl_peer_cert }}",
        "--peer-trusted-ca-file","{{ etcd_data_ssl_internal }}/{{ etcd_data_ssl_ca_dir }}/{{ etcd_data_ssl_ca_cert }}",
        "--debug"
    ]
