---

- name: Generate peer certificate private key
  openssl_privatekey:
    path: "{{ etcd_data_ssl_dir }}/{{ ansible_hostname }}/{{ ansible_hostname }}-peer-client.key"
  tags:
    - certificates
    - client

- name: Generate peer certificate CSR
  openssl_csr:
    path: "{{ etcd_data_ssl_dir }}/{{ ansible_hostname }}/{{ ansible_hostname }}-peer-client.csr"
    privatekey_path: "{{ etcd_data_ssl_dir }}/{{ ansible_hostname }}/{{ ansible_hostname }}-peer-client.key"
    common_name: "{{ ansible_hostname }}"
    subject_alt_name:
      - "IP:{{ hostvars[inventory_hostname]['ansible_%s' | format(etcd_network_interface)].ipv4.address }}"
      - "DNS:{{ ansible_hostname }}"
    basic_constraints:
      - CA:false
    basic_constraints_critical: true
    extended_key_usage:
      - clientAuth
      - serverAuth
    force: false
  tags:
    - certificates
    - client

- name: Generate peer certificate
  openssl_certificate:
    path: "{{ etcd_data_ssl_dir }}/{{ ansible_hostname }}/{{ ansible_hostname }}-peer-client.pem"
    csr_path: "{{ etcd_data_ssl_dir }}/{{ ansible_hostname }}/{{ ansible_hostname }}-peer-client.csr"
    ownca_path: "{{ etcd_data_ssl_dir }}/ca/{{ etcd_data_ssl_ca_cert }}"
    ownca_privatekey_path: "{{ etcd_data_ssl_dir }}/ca/{{ etcd_data_ssl_ca_key }}"
    provider: ownca
    force: false
  tags:
    - certificates
    - client
