---

- name: Generate CA private key
  become: false
  local_action:
    module: openssl_privatekey
    path: certificates/etcd/ca.key
  tags:
    - certificates
    - ca

## Key usage, as defined in RFC-3280 ( http://www.ietf.org/rfc/rfc3280.txt ), 4.2.1.3 section
- name: Generate CA CSR
  become: false
  local_action:
    module: openssl_csr
    state: present
    path: certificates/etcd/ca.csr
    privatekey_path: certificates/etcd/ca.key
    common_name: Ansible
    basic_constraints:
      - CA:true
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
      - cRLSign
    key_usage_critical: true
    extended_key_usage:
      - clientAuth
      - serverAuth
    force: false
  tags:
    - certificates
    - ca

- name: Generate a Self Signed CA certificate
  become: false
  local_action:
    module: openssl_certificate
    state: present
    path: certificates/etcd/ca.pem
    privatekey_path: certificates/etcd/ca.key
    csr_path: "certificates/etcd/ca.csr"
    provider: selfsigned
    force: false
  tags:
    - certificates
    - ca

- name: Copy generated CA files
  copy: 
    src: "{{ item }}"
    dest: "{{ etcd_data_ssl_dir }}/ca"
  with_items:
    - certificates/etcd/ca.pem
    - certificates/etcd/ca.key
  tags:
    - certificates
    - ca
