---

- name: Generate CA private key
  become: false
  local_action:
    module: openssl_privatekey
    path: "{{ etcd_ssl_local_dir }}/{{ etcd_data_ssl_ca_key }}"
  tags:
    - certificates
    - ca

## Key usage, as defined in RFC-3280 ( http://www.ietf.org/rfc/rfc3280.txt ), 4.2.1.3 section
- name: Generate CA CSR
  become: false
  local_action:
    module: openssl_csr
    state: present
    path: "{{ etcd_ssl_local_dir }}/{{ etcd_data_ssl_ca_csr }}"
    privatekey_path: "{{ etcd_ssl_local_dir }}/{{ etcd_data_ssl_ca_key }}"
    common_name: "{{ etcd_data_ssl_ca_cn }}"
    basic_constraints:
      - CA:true
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
      - cRLSign
    key_usage_critical: true
    extended_key_usage:
      - clientAuth
      - serverAuth
    force: false
  tags:
    - certificates
    - ca

- name: Generate a Self Signed CA certificate
  become: false
  local_action:
    module: openssl_certificate
    state: present
    path: "{{ etcd_ssl_local_dir }}/{{ etcd_data_ssl_ca_cert }}"
    privatekey_path: "{{ etcd_ssl_local_dir }}/{{ etcd_data_ssl_ca_key }}"
    csr_path: "{{ etcd_ssl_local_dir }}/{{ etcd_data_ssl_ca_csr }}"
    provider: selfsigned
    force: false
  tags:
    - certificates
    - ca

- name: Copy generated CA files
  copy: 
    src: "{{ item }}"
    dest: "{{ etcd_data_ssl_dir }}/{{ etcd_data_ssl_ca_dir }}"
  with_items:
    - "{{ etcd_ssl_local_dir }}/{{ etcd_data_ssl_ca_cert }}"
    - "{{ etcd_ssl_local_dir }}/{{ etcd_data_ssl_ca_key }}"
  tags:
    - certificates
    - ca
